openapi: 3.0.0

info:
  version: 1.0.0
  title: SWAGGER API DOCS
  description: good luck =)

paths:
  /user/all:
    get:
      summary: Returns list of users
      description: Returns list of users with some data
      operationId: getAllUsers
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Users"
        "400":
          description: Invalid ID supplied
        "404":
          description: User Preference not found
        "500":
          description: Server internal error

components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
        - email
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
          format: email

    Users:
      type: array
      items:
        $ref: "#/components/schemas/User"
