version: "3.8"

volumes:
  storage_data: {}

services:
  database:
    image: postgres:15.3-alpine3.18
    container_name: database
    restart: unless-stopped
    env_file:
      - ./storage/.env
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  storage:
    build:
      context: ./storage
      dockerfile: Dockerfile.local
    container_name: storage
    depends_on:
      - database
    volumes:
      - ./storage:/storage/
    env_file:
      - ./storage/.env
    ports:
      - 4000:4000

  nginx:
    image: nginx:1.25.1-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 3000:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
