version: "3.8"

volumes:
  storage_data: {}

services:
  database:
    image: postgres:15.3-alpine3.18
    container_name: database
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  storage:
    build:
      context: ./src/services/storage
      dockerfile: Dockerfile.local
    container_name: storage
    depends_on:
      - database
    volumes:
      - ./src/services/storage:/app
    env_file:
      - .env
    ports:
      - 4000:4000

  gateway:
    build:
      context: ./
      dockerfile: Dockerfile.local
    container_name: gateway
    depends_on:
      - storage
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - 3000:3000
